const copy = {
  de: {
    product: "Incident Response",
    simulatedIncident: "SIMULIERTER VORFALL",
    openDashboard: "Kundenportal öffnen",
    refresh: "Aktualisieren",
    refreshing: "Wird aktualisiert ...",
    incidentResponse: "Service Operations",
    eyebrow: "Aktiver Workshop-Vorfall",
    resolvedEyebrow: "Verifizierter Workshop-Vorfall",
    incidentTitle: "Kundenportal zeigt Vertragstempo statt tatsächlicher Geschwindigkeit",
    incidentSummary: "Bei einer regionalen Netzstörung wird die beworbene Tarifgeschwindigkeit als aktueller Messwert angezeigt.",
    priority: "P1 Priorität",
    open: "Offen",
    resolved: "Behoben",
    service: "Betroffener Service",
    region: "Servicegebiet",
    restoration: "Voraussichtliche Entstörung",
    serviceHealth: "Servicestatus",
    currentSpeed: "Gemessene Geschwindigkeit",
    displayedSpeed: "Anzeige im Kundenportal",
    advertisedSpeed: "Beworbene Tarifgeschwindigkeit",
    degraded: "Eingeschränkt",
    connected: "Verbunden",
    networkOutageActive: "Lokale Netzstörung aktiv",
    customerSees: "Für Kunden sichtbar",
    contractedMaximum: "Maximaler Tarifwert",
    speedReduction: "unter Tarifgeschwindigkeit",
    evidenceTitle: "Was Kundinnen und Kunden sehen",
    evidenceEyebrow: "Kundenerlebnis",
    evidenceSummary: "Das Portal kennzeichnet den Anschluss als eingeschränkt, zeigt aber weiterhin den beworbenen Tarifwert an.",
    accountPreview: "Vorschau des Kundenportals",
    homeInternet: "Zuhause Internet",
    currentReading: "Aktuelle Anzeige",
    actuallyMeasured: "Tatsächlich gemessen",
    mismatchDetected: "Widersprüchliche Geschwindigkeitsanzeige erkannt",
    consistentDisplay: "Geschwindigkeitsanzeige stimmt mit dem Messwert überein",
    customerImpact: "Auswirkung auf Kundinnen und Kunden",
    customerImpactBody: "Die falsche Hauptanzeige lässt den Anschluss trotz aktiver Störung wesentlich schneller erscheinen und widerspricht der Diagnose des Service-Assistenten.",
    resolvedImpactBody: "Die Hauptanzeige entspricht jetzt dem Messwert. Der regionale Netzausfall bleibt unabhängig davon sichtbar.",
    reproductionTitle: "Reproduktion",
    reproductionSteps: [
      "Kundenportal öffnen und die Karte Zuhause Internet suchen.",
      "Den Status Eingeschränkt und den angezeigten Geschwindigkeitswert vergleichen.",
      "Den Service-Assistenten nach der langsamen Internetverbindung fragen.",
      "Die Portal-Anzeige mit currentSpeedMbps aus den Kontodaten vergleichen.",
    ],
    technicalTitle: "Technische Untersuchung",
    technicalEyebrow: "Für die Hotfix-Übergabe",
    technicalSummary: "Die Kontodaten enthalten beide Werte. Die gemeinsame Präsentationslogik wählt derzeit den beworbenen Tarifwert.",
    sourceAccount: "Fiktive Kontodaten",
    sourcePresentation: "Gemeinsame Präsentationslogik",
    expectedFix: "Erwartetes Verhalten",
    expectedItems: [
      "12 Mbit/s als tatsächlich gemessene Geschwindigkeit hervorheben.",
      "100 Mbit/s separat als beworbenen Tarifwert kennzeichnen.",
      "Den Status Eingeschränkt und die aktive Netzstörung beibehalten.",
      "Deutsch, Englisch und bestehende Serviceabläufe unverändert erhalten.",
    ],
    timelineTitle: "Vorfallverlauf",
    timelineEyebrow: "Nachvollziehbare Signale",
    networkDetected: "Regionale Netzstörung erkannt",
    networkDetail: "Der Anschluss ist erreichbar, arbeitet aber mit reduzierter Geschwindigkeit.",
    discrepancyDetected: "Abweichung im Kundenportal bestätigt",
    discrepancyDetail: "Die aktuelle Portal-Anzeige stimmt nicht mit der gemessenen Verbindungsgeschwindigkeit überein.",
    correctionVerified: "Korrekte Kundenanzeige verifiziert",
    correctionDetail: "Portal-Anzeige und Messwert stimmen überein. Die regionale Störung bleibt getrennt erfasst.",
    awaitingFix: "Isolierter Hotfix ausstehend",
    awaitingDetail: "Die Vorfallbehebung kann parallel zur laufenden Produktentwicklung in einem separaten Worktree erfolgen.",
    liveVerification: "Live-Prüfung",
    pending: "Ausstehend",
    verificationTitle: "Live-Verifizierung",
    verificationEyebrow: "Ergebnis aus realem Demo-Zustand",
    verificationOpen: "Die Anzeige weicht weiterhin vom Messwert ab.",
    verificationResolved: "Die Anzeige entspricht dem tatsächlichen Messwert.",
    outageBoundary: "Das Beheben der Anzeige behebt nicht die zugrunde liegende simulierte Netzstörung.",
    dataBoundary: "Alle Personen, Servicedaten und Vorfälle sind fiktiv. Es bestehen keine Verbindungen zu realen Netzsystemen.",
    checkedAt: "Zuletzt geprüft",
    loading: "Vorfall wird geladen ...",
    errorLoading: "Der simulierte Vorfall konnte nicht geladen werden.",
    retry: "Erneut versuchen",
  },
  en: {
    product: "Incident Response",
    simulatedIncident: "SIMULATED INCIDENT",
    openDashboard: "Open customer dashboard",
    refresh: "Refresh",
    refreshing: "Refreshing ...",
    incidentResponse: "Service Operations",
    eyebrow: "Active workshop incident",
    resolvedEyebrow: "Verified workshop incident",
    incidentTitle: "Customer dashboard shows plan speed instead of actual connection speed",
    incidentSummary: "During a regional network outage, the advertised plan speed is presented as the current measured connection speed.",
    priority: "P1 priority",
    open: "Open",
    resolved: "Resolved",
    service: "Affected service",
    region: "Service area",
    restoration: "Estimated restoration",
    serviceHealth: "Service status",
    currentSpeed: "Measured connection speed",
    displayedSpeed: "Displayed in customer dashboard",
    advertisedSpeed: "Advertised plan speed",
    degraded: "Degraded",
    connected: "Connected",
    networkOutageActive: "Local network outage active",
    customerSees: "Visible to the customer",
    contractedMaximum: "Maximum advertised plan speed",
    speedReduction: "below advertised plan speed",
    evidenceTitle: "What the customer sees",
    evidenceEyebrow: "Customer experience",
    evidenceSummary: "The dashboard correctly labels the connection as limited but still displays the advertised plan speed.",
    accountPreview: "Customer dashboard preview",
    homeInternet: "Home internet",
    currentReading: "Current display",
    actuallyMeasured: "Actually measured",
    mismatchDetected: "Inconsistent speed display detected",
    consistentDisplay: "Displayed speed matches the measured connection",
    customerImpact: "Customer impact",
    customerImpactBody: "The incorrect primary speed makes the connection appear substantially faster despite an active outage and conflicts with the assistant's service diagnosis.",
    resolvedImpactBody: "The primary display now matches the measured connection speed. The regional outage remains visible as a separate service issue.",
    reproductionTitle: "Reproduction steps",
    reproductionSteps: [
      "Open the customer dashboard and locate the home internet account card.",
      "Compare the limited connection status with the prominently displayed speed.",
      "Ask the service assistant about the slow home internet connection.",
      "Compare the dashboard value with currentSpeedMbps in the account data.",
    ],
    technicalTitle: "Engineering investigation",
    technicalEyebrow: "Ready for an isolated hotfix",
    technicalSummary: "The account contains both values. The shared presentation logic currently selects the advertised plan speed.",
    sourceAccount: "Fictional account data",
    sourcePresentation: "Shared presentation logic",
    expectedFix: "Expected behavior",
    expectedItems: [
      "Display 12 Mbps prominently as the actual measured connection speed.",
      "Label 100 Mbps separately as the advertised plan speed.",
      "Preserve the degraded status and the active regional outage.",
      "Keep English, German, and existing customer-service workflows intact.",
    ],
    timelineTitle: "Incident timeline",
    timelineEyebrow: "Evidence-backed signals",
    networkDetected: "Regional network issue detected",
    networkDetail: "The connection remains available but is operating at a reduced speed.",
    discrepancyDetected: "Customer-dashboard inconsistency confirmed",
    discrepancyDetail: "The displayed account-card value does not match the measured connection speed.",
    correctionVerified: "Correct customer-facing display verified",
    correctionDetail: "The dashboard value now matches the measured speed. The regional outage remains tracked separately.",
    awaitingFix: "Waiting for an isolated hotfix",
    awaitingDetail: "Incident remediation can run in a separate worktree while feature development continues.",
    liveVerification: "Live verification",
    pending: "Pending",
    verificationTitle: "Live verification",
    verificationEyebrow: "Derived from actual demo state",
    verificationOpen: "The displayed speed still differs from the measured connection speed.",
    verificationResolved: "The displayed speed matches the actual measured connection speed.",
    outageBoundary: "Fixing the displayed speed does not resolve the separate simulated network outage.",
    dataBoundary: "All customer identities, service data, and incidents are fictional. No real carrier systems are connected.",
    checkedAt: "Last checked",
    loading: "Loading incident ...",
    errorLoading: "The simulated incident could not be loaded.",
    retry: "Try again",
  },
};

export function getIncidentCopy(locale) {
  return copy[locale] ?? copy.en;
}
